# Generated by Django 4.2.2 on 2023-06-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=25, null=True)),
                ('job_type', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=55, null=True)),
                ('companyname', models.CharField(max_length=50, null=True)),
                ('company_description', models.CharField(max_length=55, null=True)),
                ('website', models.CharField(max_length=15, null=True)),
                ('fb_username', models.CharField(max_length=15, null=True)),
                ('tw_username', models.CharField(max_length=15, null=True)),
                ('lk_username', models.CharField(max_length=15, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.employer')),
            ],
        ),
    ]
