# Generated by Django 4.2.2 on 2023-06-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
