# Generated by Django 4.2.2 on 2023-06-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0003_job_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField(null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=15, null=True)),
                ('experience', models.CharField(max_length=150, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('resume', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.jobseeker')),
            ],
        ),
    ]
