# Generated by Django 4.2.2 on 2023-06-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0004_job_experience_job_last_date_job_published_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='jobseeker',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='user',
            new_name='jobseeker',
        ),
        migrations.AddField(
            model_name='book',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.employer'),
        ),
    ]
