# Generated by Django 4.2.2 on 2023-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0006_remove_book_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
